version: '3'

services:
      
  data-central-hiring:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3021:3021"
    volumes:
      - .:/usr/src/app
    env_file:
      - .env

  data-central-database-hiring:
    image: postgres
    env_file:
      - .env.database
    volumes:
      - db_data_central_hiring:/var/lib/postgresql/data

volumes:
  db_data_central_hiring:
